
import type { Patient } from '@/types/patient';

type MockPatientData = Omit<Patient, 'id' | 'bedNumber' | 'roomDesignation' | 'gridRow' | 'gridColumn' | 'admitDate' | 'dischargeDate'>;

export const mockPatientData: MockPatientData[] = [
  {
    name: "Eleanor Vance",
    age: 72,
    gender: "Female",
    chiefComplaint: "COPD exacerbation",
    ldas: ["2L NC", "PIV R AC"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "DNR/DNI",
    orientationStatus: "x3",
    assignedNurse: "RN Alice",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Family meeting at 14:00. Awaiting chest X-ray results.",
  },
  {
    name: "Marcus Holloway",
    age: 45,
    gender: "Male",
    chiefComplaint: "Post-op appendectomy",
    ldas: ["PIV L Hand", "JP Drain"],
    diet: "Clear Liquids",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Bob",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Incentive spirometer q1h. Medicate for pain before ambulation.",
  },
  {
    name: "Sofia Rossi",
    age: 81,
    gender: "Female",
    chiefComplaint: "Altered mental status",
    ldas: ["Foley Catheter"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    assignedNurse: "RN Charlie",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Suspected UTI. Urine culture sent. Needs 1:1 sitter.",
  },
  {
    name: "David Chen",
    age: 58,
    gender: "Male",
    chiefComplaint: "Chest pain, r/o MI",
    ldas: ["2 PIVs (AC)", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN David",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Troponins q6h. NTG PRN.",
  },
  {
    name: "Jasmine Kaur",
    age: 34,
    gender: "Female",
    chiefComplaint: "Pneumonia",
    ldas: ["PIV L Wrist"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Mallory",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "On IV Levaquin. Monitor for respiratory distress.",
  },
  {
    name: "Robert Miller",
    age: 67,
    gender: "Male",
    chiefComplaint: "Cellulitis LLE",
    ldas: ["PIV R Hand"],
    diet: "Diabetic Diet (ADA)",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    assignedNurse: "RN Judy",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Elevate LLE. Outline redness.",
  },
  {
    name: "Isabella Garcia",
    age: 29,
    gender: "Female",
    chiefComplaint: "Migraine with aura",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Quiet, dark room. IV fluids for hydration.",
  },
  {
    name: "Liam O'Connell",
    age: 78,
    gender: "Male",
    chiefComplaint: "Fall at home, hip fx",
    ldas: ["PIV L FA"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Ortho consult pending. Scheduled for surgery in AM.",
  },
  {
    name: "Ava Nguyen",
    age: 52,
    gender: "Female",
    chiefComplaint: "New onset seizures",
    ldas: ["PIV R AC"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Keppra load given. EEG scheduled.",
  },
  {
    name: "Jackson Williams",
    age: 63,
    gender: "Male",
    chiefComplaint: "GI Bleed",
    ldas: ["2 large bore PIVs"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "DNR/DNI",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Serial H&H. GI consult placed.",
  },
  {
    name: "Olivia Brown",
    age: 40,
    gender: "Female",
    chiefComplaint: "DKA",
    ldas: ["Insulin Drip", "PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Hourly glucose checks. Monitor potassium levels.",
  },
  {
    name: "Noah Patel",
    age: 88,
    gender: "Male",
    chiefComplaint: "Dehydration",
    ldas: ["PIV L Hand"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Encourage PO fluids. IV fluids running at 75ml/hr.",
  },
  {
    name: "Emma Wilson",
    age: 19,
    gender: "Female",
    chiefComplaint: "Suicidal Ideation",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "1:1 sitter for safety. Psych consult placed.",
  },
  {
    name: "Lucas Martinez",
    age: 65,
    gender: "Male",
    chiefComplaint: "A-fib with RVR",
    ldas: ["PIV", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Cardizem drip. Monitor heart rate and BP closely.",
  },
  {
    name: "Mia Johnson",
    age: 75,
    gender: "Female",
    chiefComplaint: "CVA",
    ldas: ["NG Tube", "PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Speech therapy consult for swallow evaluation.",
  },
  {
    name: "Ethan Taylor",
    age: 31,
    gender: "Male",
    chiefComplaint: "Kidney stone",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Strain all urine. Pain management with Toradol.",
  },
  {
    name: "Avery Scott",
    age: 25,
    gender: "Female",
    chiefComplaint: "Asthma exacerbation",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Continuous nebulizer treatments. Monitor O2 sats.",
  },
  {
    name: "Benjamin Green",
    age: 92,
    gender: "Male",
    chiefComplaint: "Failure to thrive",
    ldas: [],
    diet: "Pureed",
    mobility: "Assisted",
    codeStatus: "DNR",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Hospice consult. Focus on comfort measures.",
  },
  {
    name: "Chloe King",
    age: 48,
    gender: "Female",
    chiefComplaint: "Pancreatitis",
    ldas: ["PIV"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Aggressive IV fluids. Pain management with Dilaudid PCA.",
  },
  {
    name: "Daniel Wright",
    age: 55,
    gender: "Male",
    chiefComplaint: "Alcohol withdrawal",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "CIWA protocol. Ativan PRN.",
  },
  {
    name: "Harper Lee",
    age: 22,
    gender: "Female",
    chiefComplaint: "Anorexia nervosa",
    ldas: ["Central Line"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Monitor for refeeding syndrome. Strict I&Os.",
  },
  {
    name: "Logan Hill",
    age: 38,
    gender: "Male",
    chiefComplaint: "Deep vein thrombosis",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Heparin drip. Monitor PTT. No IM injections.",
  },
  {
    name: "Evelyn Reed",
    age: 85,
    gender: "Female",
    chiefComplaint: "Sepsis",
    ldas: ["Central Line", "Foley"],
    diet: "NPO (Nothing by mouth)",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Broad-spectrum antibiotics. Monitor lactate levels.",
  },
  {
    name: "Mason Cook",
    age: 50,
    gender: "Male",
    chiefComplaint: "Liver failure",
    ldas: ["PICC Line"],
    diet: "Renal Diet",
    mobility: "Assisted",
    codeStatus: "DNR/DNI",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Monitor for asterixis. Lactulose for ammonia levels.",
  },
  {
    name: "Scarlett Bell",
    age: 68,
    gender: "Female",
    chiefComplaint: "Hypertensive crisis",
    ldas: ["Arterial Line", "PIV"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Nicardipine drip. Frequent neuro checks.",
  },
  {
    name: "Grayson Morgan",
    age: 71,
    gender: "Male",
    chiefComplaint: "Urinary retention",
    ldas: ["Foley Catheter"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Urology consult. Flomax started.",
  },
  {
    name: "Zoe Cooper",
    age: 28,
    gender: "Female",
    chiefComplaint: "Sickle cell crisis",
    ldas: ["PIV"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Pain management and hydration are priorities.",
  },
  {
    name: "Caleb Rivera",
    age: 60,
    gender: "Male",
    chiefComplaint: "Gout flare",
    ldas: [],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Colchicine and NSAIDs. Bed cradle to keep sheets off feet.",
  },
  {
    name: "Lillian Powell",
    age: 95,
    gender: "Female",
    chiefComplaint: "Social admit",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "DNR",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Awaiting nursing home placement. Case management involved.",
  },
  {
    name: "Henry Long",
    age: 82,
    gender: "Male",
    chiefComplaint: "Congestive heart failure",
    ldas: ["PIV"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Strict I&Os. Daily weights. Lasix IV.",
  },
  {
    name: "Aurora Hughes",
    age: 44,
    gender: "Female",
    chiefComplaint: "Post-op Mastectomy",
    ldas: ["JP Drain", "PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "No BPs or IVs in left arm. Monitor drain output.",
  },
  {
    name: "Wyatt Peterson",
    age: 77,
    gender: "Male",
    chiefComplaint: "Shingles",
    ldas: [],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Airborne and contact precautions. Acyclovir administered.",
  },
  {
    name: "Ryan Miller",
    age: 63,
    gender: "Male",
    chiefComplaint: "Cellulitis R leg",
    ldas: ["PIV R AC", "Wound VAC"],
    diet: "Diabetic",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Name alert: similar to Robert Miller. IV antibiotics q8h.",
  },
  {
    name: "Daniel Chen",
    age: 52,
    gender: "Male",
    chiefComplaint: "GI bleed",
    ldas: ["2 PIVs", "NG Tube"],
    diet: "NPO",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Name alert: similar to David Chen. H&H trending.",
  },
  {
    name: "Emily Wilson",
    age: 29,
    gender: "Female",
    chiefComplaint: "Postpartum hemorrhage",
    ldas: ["PIV", "Foley"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Name alert: similar to Emma Wilson. L&D follow-up.",
  },
  {
    name: "Patricia Nguyen",
    age: 68,
    gender: "Female",
    chiefComplaint: "Stroke, L MCA",
    ldas: ["PIV", "Telemetry", "Foley"],
    diet: "Pureed",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: true,
    isComfortCareDNR: false,
    notes: "Neuro checks q1h. Speech therapy eval pending.",
  },
  {
    name: "Thomas Brooks",
    age: 55,
    gender: "Male",
    chiefComplaint: "DKA",
    ldas: ["Insulin drip", "PIV"],
    diet: "Diabetic",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Hourly glucose checks. Endocrine consult.",
  },
  {
    name: "Rachel Foster",
    age: 34,
    gender: "Female",
    chiefComplaint: "Ectopic pregnancy",
    ldas: ["PIV"],
    diet: "Clear Liquids",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Post-op laparoscopy. Pain management PRN.",
  },
  {
    name: "George Sullivan",
    age: 88,
    gender: "Male",
    chiefComplaint: "Hip fracture s/p ORIF",
    ldas: ["Epidural PCA", "PIV"],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "DNR",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "PT eval tomorrow. DNR bracelet verified.",
  },
  {
    name: "Natalie Price",
    age: 41,
    gender: "Female",
    chiefComplaint: "Pancreatitis",
    ldas: ["PIV", "NG Tube"],
    diet: "NPO",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Lipase trending down. Pain scale q4h.",
  },
  {
    name: "Kevin O'Brien",
    age: 49,
    gender: "Male",
    chiefComplaint: "Alcohol withdrawal",
    ldas: ["CIWA scale", "PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: true,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "CIWA q2h. Thiamine and folate.",
  },
  {
    name: "Angela Torres",
    age: 57,
    gender: "Female",
    chiefComplaint: "C. diff colitis",
    ldas: ["PIV"],
    diet: "Clear Liquids",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: true,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Contact precautions. Dedicated commode.",
  },
  {
    name: "Samuel Reed",
    age: 71,
    gender: "Male",
    chiefComplaint: "A-fib RVR",
    ldas: ["Telemetry", "PIV"],
    diet: "Cardiac Diet",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "On amiodarone drip. Rate control goal <110.",
  },
  {
    name: "Christine Walsh",
    age: 46,
    gender: "Female",
    chiefComplaint: "Anaphylaxis",
    ldas: ["Epi pen at bedside", "PIV"],
    diet: "Allergen-free",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Allergy band: penicillin, shellfish. Observe 24h.",
  },
  {
    name: "Derek Hammond",
    age: 38,
    gender: "Male",
    chiefComplaint: "Motorcycle trauma",
    ldas: ["Chest tube", "2 PIVs", "Foley"],
    diet: "NPO",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Trauma surgery following. Chest tube to suction.",
  },
  {
    name: "Monica Hayes",
    age: 62,
    gender: "Female",
    chiefComplaint: "Breast CA chemo",
    ldas: ["PICC line", "Port-a-cath"],
    diet: "Regular",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Neutropenic precautions if ANC low. Onc follow-up.",
  },
  {
    name: "Victor Lang",
    age: 83,
    gender: "Male",
    chiefComplaint: "Aspiration pneumonia",
    ldas: ["O2 4L NC", "PIV"],
    diet: "Pureed",
    mobility: "Bed Rest",
    codeStatus: "DNR/DNI",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Speech therapy swallow study. Comfort measures PRN.",
  },
  {
    name: "Hannah Kim",
    age: 22,
    gender: "Female",
    chiefComplaint: "Eating disorder refeeding",
    ldas: ["PIV"],
    diet: "Mechanical soft",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: true,
    isComfortCareDNR: false,
    notes: "1:1 observation. Refeeding protocol.",
  },
  {
    name: "Philip Grant",
    age: 59,
    gender: "Male",
    chiefComplaint: "CABG post-op day 2",
    ldas: ["Chest tubes", "Arterial line", "Telemetry"],
    diet: "Cardiac Diet",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Sternal precautions. Incentive spirometer.",
  },
  {
    name: "Janet Coleman",
    age: 75,
    gender: "Female",
    chiefComplaint: "UTI with delirium",
    ldas: ["Foley", "PIV"],
    diet: "Regular",
    mobility: "Assisted",
    codeStatus: "Full Code",
    orientationStatus: "x2",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Delirium precautions. Reorient frequently.",
  },
  {
    name: "Marcus Webb",
    age: 43,
    gender: "Male",
    chiefComplaint: "Kidney stone",
    ldas: ["PIV"],
    diet: "Clear Liquids",
    mobility: "Independent",
    codeStatus: "Full Code",
    orientationStatus: "x4",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: false,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "Strain all urine. Toradol PRN.",
  },
  {
    name: "Laura Bennett",
    age: 66,
    gender: "Female",
    chiefComplaint: "COPD on BiPAP",
    ldas: ["BiPAP", "PIV"],
    diet: "Low sodium",
    mobility: "Bed Rest",
    codeStatus: "Full Code",
    orientationStatus: "x3",
    isFallRisk: false,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: false,
    notes: "ABG morning draw. Wean BiPAP per RT.",
  },
  {
    name: "Richard Vaughn",
    age: 91,
    gender: "Male",
    chiefComplaint: "Failure to thrive",
    ldas: [],
    diet: "Regular",
    mobility: "Bed Rest",
    codeStatus: "DNR/DNI",
    orientationStatus: "x1",
    isFallRisk: true,
    isSeizureRisk: false,
    isAspirationRisk: true,
    isIsolation: false,
    isInRestraints: false,
    isComfortCareDNR: true,
    notes: "Hospice consult. Family at bedside.",
  },
];
